require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
